FROM openjdk:8-alpine
WORKDIR /work
VOLUME ["/earning/logs","/earning/static"]
RUN ln -sf /usr/share/zoneinfo/Africa/Accra /etc/localtime
RUN echo "Africa/Accra" > /etc/timezone
RUN apk add --update ttf-dejavu fontconfig
RUN apk add tini

EXPOSE 80

ENTRYPOINT ["tini"]

ADD target/online-earning-1.0.jar .

ENTRYPOINT tini java -Djava.security.egd=file:/dev/./urandom  -jar -Xmx8000M -Xms8000M -Dspring.profiles.active=prdghana online-earning-1.0.jar